theme: jekyll-theme-architect
url: "https://pdonnelly3.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-press
  - amp-jekyll
jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
ampdir: '/amp'
